{% set version = '0.3.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-manhattanly
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/manhattanly_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/manhattanly/manhattanly_{{ version }}.tar.gz
  sha256: 1007daed593ee6d3ad7dab932fc6ffb177fc8235f43aee73b4db3b84bfdbf800

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat (>= 3.0.0), knitr, rmarkdown, covr
requirements:
  build:
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-ggplot2
    - r-magrittr
    - r-plotly

  run:
    - r-base
    - r-ggplot2
    - r-magrittr
    - r-plotly

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('manhattanly')"           # [not win]
    - "\"%R%\" -e \"library('manhattanly')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/sahirbhatnagar/manhattanly/, https://sahirbhatnagar.com/manhattanly/
  license: MIT
  summary: Create interactive manhattan, Q-Q and volcano plots that are usable from the R console,
    in 'Dash' apps, in the 'RStudio' viewer pane, in 'R Markdown' documents, and in
    'Shiny' apps. Hover the mouse pointer over a point to show details or drag a rectangle
    to zoom. A manhattan plot is a popular graphical method for visualizing results
    from high-dimensional data analysis such as a (epi)genome wide association study
    (GWAS or EWAS), in which p-values, Z-scores, test statistics are plotted on a scatter
    plot against their genomic position. Manhattan plots are used for visualizing potential
    regions of interest in the genome that are associated with a phenotype. Interactive
    manhattan plots allow the inspection of specific value (e.g. rs number or gene name)
    by hovering the mouse over a cell, as well as zooming into a region of the genome
    (e.g. a chromosome) by dragging a rectangle around the relevant area. This work
    is based on the 'qqman' package and the 'plotly.js' engine. It produces similar
    manhattan and Q-Q plots as the 'manhattan' and 'qq' functions in the 'qqman' package,
    with the advantage of including extra annotation information and interactive web-based
    visualizations directly from R. Once uploaded to a 'plotly' account, 'plotly' graphs
    (and the data behind them) can be viewed and modified in a web browser.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

