{% set version = '2.1.2' %}

package:
  name: r-signature.tools.lib
  version: {{ version|replace("-", "_") }}

source:
  git_url: https://github.com/umccr/signature.tools.lib
  git_tag: 2.1.2_Jun2022_1

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - git

  host:
    - r-base
    - bioconductor-bsgenome
    - bioconductor-biocgenerics
    - r-gensa
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-iranges
    - r-nmf
    - r-nnlm
    - r-rcircos
    - bioconductor-summarizedexperiment
    - bioconductor-variantannotation
    - r-cluster
    - r-combinat
    - r-doparallel
    - r-dorng
    - r-foreach
    - r-ggplot2
    - r-gmp
    - r-limsolve
    - r-lpsolve
    - r-nnls
    - r-plyr
    - r-readr
    - r-scales

  run:
    - r-base
    - bioconductor-bsgenome
    - bioconductor-biocgenerics
    - r-gensa
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-iranges
    - r-nmf
    - r-nnlm
    - r-rcircos
    - bioconductor-summarizedexperiment
    - bioconductor-variantannotation
    - r-cluster
    - r-combinat
    - r-doparallel
    - r-dorng
    - r-foreach
    - r-ggplot2
    - r-gmp
    - r-limsolve
    - r-lpsolve
    - r-nnls
    - r-plyr
    - r-readr
    - r-scales

test:
  commands:
    - $R -e "library('signature.tools.lib')"
about:
  home: https://github.com/umccr/signature.tools.lib
  license: see LICENCE file
  summary: R package with useful functions for mutational signatures analysis.
  license_family: OTHER
