package:
  name: r-nnlm
  version: 0.4.4

source:
  git_url: https://github.com/linxihui/NNLM
  git_tag: 0.4.4

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf
    - automake
    - pkg-config
    - make

  host:
    - r-base
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppprogress

  run:
    - r-base
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppprogress

test:
  commands:
    - $R -e "library('NNLM')"

about:
  home: https://github.com/linxihui/NNLM
  license: BSD_2_clause + file LICENSE
  summary: This is a package for Non-Negative Linear Models (NNLM). It implements
    fast sequential coordinate descent algorithms for non-negative linear regression
    and non-negative matrix factorization (NMF). It supports mean square error and
    Kullback-Leibler divergence loss. Many other features are also implemented,
    including missing value imputation, domain knowledge integration,
    designable W and H matrices and multiple forms of regularizations.
  license_family: BSD
