name: conda-build

on:
  workflow_dispatch:
    inputs:
      conda_pkg:
        type: choice
        description: conda pkg to build
        required: true
        options:
        - r-chord
        - r-mutsigextractor
        - r-nnlm
        - r-signature.tools.lib
      r_version:
        type: choice
        description: R version to use
        required: true
        default: "4.3"
        options:
        - "4.1"
        - "4.2"
        - "4.3"



env:
  atoken: ${{ secrets.ANACONDA_UPLOAD_TOKEN }}
jobs:
  conda-build:
    name: Conda Package Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: MicroMamba setup
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: cbuildenv
          create-args:
            conda-build
            conda-verify
            anaconda-client
            boa
      - name: 🐍 Conda pkg build and upload
        run: |
          conda mambabuild --R ${{ github.event.inputs.r_version }} ${{ github.event.inputs.conda_pkg }} --token ${atoken}
